#ifndef COMMON_H
#define COMMON_H

#define PROXY_REQUEST_BUFFER_SIZE 8192
#define PROXY_SOCKET_TIMEOUT_MS 5000
#define PROXY_ACCEPT_POLL_TIMEOUT_MS 500
#define PROXY_THREAD_POOL_QUEUE_CAPACITY 64

#endif
